services:
  searxng:
    build:
      context: .
      dockerfile: searxng.dockerfile
    expose:
      - 3002
    ports:
      - 3002:8080
    networks:
      - perplexity

  perplexity-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    expose:
      - 3001
    ports:
      - 3001:3001
    networks:
      - perplexity

  perplexity-frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    depends_on:
      - perplexity-backend
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - perplexity

networks:
  perplexity: